force-app/main/default/objects/Habilidad__c/Habilidad__c.object-meta.xml
<CustomObject>
    <label>Habilidad</label>
    <nameField>
        <label>Habilidad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movimiento__c/Movimiento__c.object-meta.xml
<CustomObject>
    <label>Movimiento</label>
    <nameField>
        <label>Movimiento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movimientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movimiento__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <label>ExtId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Altura__c.field-meta.xml
<CustomField>
    <fullName>Altura__c</fullName>
    <label>Altura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Ataque__c.field-meta.xml
<CustomField>
    <fullName>Ataque__c</fullName>
    <label>Ataque</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Defensa__c.field-meta.xml
<CustomField>
    <fullName>Defensa__c</fullName>
    <label>Defensa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Habilidad__c.field-meta.xml
<CustomField>
    <fullName>Habilidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidad</label>
    <referenceTo>Habilidad__c</referenceTo>
    <relationshipLabel>Pokemon</relationshipLabel>
    <relationshipName>Pokemon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Slot1__c.field-meta.xml
<CustomField>
    <fullName>Slot1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Slot1</label>
    <referenceTo>Movimiento__c</referenceTo>
    <relationshipLabel>Pokemon</relationshipLabel>
    <relationshipName>Pokemon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Slot2__c.field-meta.xml
<CustomField>
    <fullName>Slot2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Slot2</label>
    <referenceTo>Movimiento__c</referenceTo>
    <relationshipLabel>Pokemon (Slot2)</relationshipLabel>
    <relationshipName>Pokemon1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Slot3__c.field-meta.xml
<CustomField>
    <fullName>Slot3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Slot3</label>
    <referenceTo>Movimiento__c</referenceTo>
    <relationshipLabel>Pokemon (Slot3)</relationshipLabel>
    <relationshipName>Pokemon2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Slot4__c.field-meta.xml
<CustomField>
    <fullName>Slot4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Slot4</label>
    <referenceTo>Movimiento__c</referenceTo>
    <relationshipLabel>Pokemon (Slot4)</relationshipLabel>
    <relationshipName>Pokemon3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Tipos__c.field-meta.xml
<CustomField>
    <fullName>Tipos__c</fullName>
    <label>Tipos</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Velocidad__c.field-meta.xml
<CustomField>
    <fullName>Velocidad__c</fullName>
    <label>Velocidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Vida__c.field-meta.xml
<CustomField>
    <fullName>Vida__c</fullName>
    <label>Vida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/pokemonBatch.cls
global class pokemonBatch implements Database.Batchable<Integer>, Database.AllowsCallouts, Database.Stateful {
    global Iterable<Integer> start(Database.BatchableContext bc){
        List<Integer> indices = new List<Integer>();
        for (Integer i = 1; i <=898; i++) {
            indices.add(i);
        }
        return indices;
    }
    global void execute(Database.BatchableContext bc, List<Integer> indices) {
        
        Map<String, Object> result  = new Map <String,Object>();
        
        String name = '';
        List<Pokemon__c> pokemons = new List<Pokemon__c>();
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        HttpResponse response = new HttpResponse();
        request.setMethod('GET');                       
        for(Integer i : indices){
            request.setEndpoint('https://pokeapi.co/api/v2/pokemon/' + i);
            response = http.send(request);
            if(response.getStatusCode() == 200 ){
                Pokemon__c pokemon = new Pokemon__c();
                result = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                name = (String)result.get('name');
                Habilidad__c abl = PokemonController.matchHabiliti(result);
                Map<String, Integer> stats = PokemonController.getStats(result);
                List<Movimiento__c> mov = PokemonController.getMoves(result);
                pokemon.Name = name.capitalize();
                pokemon.Altura__c = (Double)result.get('height')/10;
                pokemon.Peso__c = (Double)result.get('weight')/10;
                pokemon.ExtId__c = (Integer)result.get('id');
                pokemon.Vida__c = stats.get('hp');
                pokemon.Ataque__c = stats.get('attack');
                pokemon.Defensa__c = stats.get('defense');
                pokemon.Velocidad__c = stats.get('speed');
                pokemon.Habilidad__c = abl.Id;
                pokemon.Image__c = PokemonController.setUrl((Integer)result.get('id'));
                pokemon.Tipos__c = PokemonController.getType(result);
                pokemon.Slot1__c = (mov.size() < 1 ? null : mov[0].id);
                pokemon.Slot2__c = (mov.size() < 1 ? null : mov[1].id);
                pokemon.Slot3__c = (mov.size() < 1 ? null : mov[2].id);
                pokemon.Slot4__c = (mov.size() < 1 ? null : mov[3].id);
                    
                pokemons.add(pokemon);              
            }         
        }	
        insert pokemons;
    }
    global void finish(Database.BatchableContext BC) {
        system.debug('finish');
    }
}