force-app/main/default/objects/Movimiento__c/Movimiento__c.object-meta.xml
<CustomObject>
    <label>Movimiento</label>
    <nameField>
        <label>Movimiento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movimientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movimiento__c/fields/Chance_de_Efecto__c.field-meta.xml
<CustomField>
    <fullName>Chance_de_Efecto__c</fullName>
    <label>Chance de Efecto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Efecto__c.field-meta.xml
<CustomField>
    <fullName>Efecto__c</fullName>
    <label>Efecto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <label>ExtId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Poder__c.field-meta.xml
<CustomField>
    <fullName>Poder__c</fullName>
    <label>Poder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Pp__c.field-meta.xml
<CustomField>
    <fullName>Pp__c</fullName>
    <label>Pp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Prioridad__c.field-meta.xml
<CustomField>
    <fullName>Prioridad__c</fullName>
    <label>Prioridad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Punteria__c.field-meta.xml
<CustomField>
    <fullName>Punteria__c</fullName>
    <label>Punteria</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Shadow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/movimientoBatchTest.cls
@isTest
public class movimientoBatchTest {
            public static testmethod void habilidadTestOk() {
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                               'Complete',
                                                               '{"name": "Pound",'+
                                                               '"id": 1,'+
                                                               '"accuracy": 100,'+
                                                               '"effect_chance": null,'+
                                                               '"priority": 0,'+
                                                               '"target": { "name": "selected-pokemon", "url": "https://pokeapi.co/api/v2/move-target/10/" },'+
                                                               '"effect_entries": [ { "effect": "Inflicts regular damage.", "language": { "name": "en", "url": "https://pokeapi.co/api/v2/language/9/" }, "short_effect": "Inflicts regular damage with no additional effect." } ],'+
                                                               '"power": 40,'+
                                                               '"pp": 35,'+
                                                               '"type": { "name": "normal", "url": "https://pokeapi.co/api/v2/type/1/" }}',
                                                               null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        test.startTest();
        Id batchJobId = Database.executeBatch(new movimientoBatch(), 1);
        test.stopTest(); 
        List<Movimiento__c> moveList = [SELECT Id, name, ExtId__c,
                                        Punteria__c, Chance_de_Efecto__c,
                                        Prioridad__c, Objetivo__c,
                                        Efecto__c, Poder__c,
                                        Pp__c, Tipo__c
                                        FROM Movimiento__c LIMIT 1];
        
        System.assertEquals(1, moveList.size(), 'los valores no coinciden');
        System.assertEquals('Pound', moveList[0].name, 'los valores no coinciden');
        System.assertEquals(1, moveList[0].ExtId__c, 'los valores no coinciden');
        System.assertEquals(100, moveList[0].Punteria__c, 'los valores no coinciden');
        System.assertEquals(null, moveList[0].Chance_de_Efecto__c, 'los valores no coinciden');
        System.assertEquals(0, moveList[0].Prioridad__c, 'los valores no coinciden');
		System.assertEquals('selected-pokemon', moveList[0].Objetivo__c, 'los valores no coinciden');
        System.assertEquals('Inflicts regular damage with no additional effect.', moveList[0].Efecto__c, 'los valores no coinciden');
        System.assertEquals(40, moveList[0].Poder__c, 'los valores no coinciden');
        System.assertEquals(35, moveList[0].Pp__c, 'los valores no coinciden');
        System.assertEquals('Normal', moveList[0].Tipo__c, 'los valores no coinciden');
                
    }
    
    public static testmethod void habilidadTestKo(){
        SingleRequestMock fakeResponse = new SingleRequestMock(404,
                                                 'Incomplete',
                                                 '',
                                                 null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
        Test.startTest();
        Id batchJobId = Database.executeBatch(new movimientoBatch(), 1);
        Test.stopTest();
        
        List<Movimiento__c> moveList = [SELECT Id, Name FROM Movimiento__c];
        
        System.assertEquals(0, moveList.size(), 'La lista tiene contenido');
    }

}