force-app/main/default/objects/Movimiento__c/Movimiento__c.object-meta.xml
<CustomObject>
    <label>Movimiento</label>
    <nameField>
        <label>Movimiento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movimientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movimiento__c/fields/Chance_de_Efecto__c.field-meta.xml
<CustomField>
    <fullName>Chance_de_Efecto__c</fullName>
    <label>Chance de Efecto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Efecto__c.field-meta.xml
<CustomField>
    <fullName>Efecto__c</fullName>
    <label>Efecto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <label>ExtId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Poder__c.field-meta.xml
<CustomField>
    <fullName>Poder__c</fullName>
    <label>Poder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Pp__c.field-meta.xml
<CustomField>
    <fullName>Pp__c</fullName>
    <label>Pp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Prioridad__c.field-meta.xml
<CustomField>
    <fullName>Prioridad__c</fullName>
    <label>Prioridad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Punteria__c.field-meta.xml
<CustomField>
    <fullName>Punteria__c</fullName>
    <label>Punteria</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Shadow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/movimientoBatch.cls
global class movimientoBatch implements Database.Batchable<Integer>, Database.AllowsCallouts, Database.Stateful {
    global Iterable<Integer> start(Database.BatchableContext bc){
        List<Integer> indices = new List<Integer>();
        for (Integer i = 1; i <= 1; i++) {
            indices.add(i);
        }
        return indices;
    }
    global void execute(Database.BatchableContext bc, List<Integer> indices) {
        String name = '';
        List<Movimiento__c> movimientos = new List<Movimiento__c>();
        List<Object> efectData = new List<Object>();
       	Map<String, Object> targetData = new Map<String, Object>();
        Map<String, Object> typeData = new Map<String, Object>();
        Map<String, Object> result  = new Map <String,Object>();
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        HttpResponse response = new HttpResponse();
        request.setMethod('GET');
        
        for(Integer i : indices){
            request.setEndpoint('https://pokeapi.co/api/v2/move/' + i);
            response = http.send(request);
            if(response.getStatusCode() == 200 ){
                result = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                name = (String)result.get('name');
                targetData = (Map<String, Object>)result.get('target');
                efectData = (List<Object>) result.get('effect_entries');
				typeData = (Map<String, Object>)result.get('type');
                Movimiento__c movimiento = new Movimiento__c(Name = name.capitalize(),
                                                             ExtId__c = (Integer)result.get('id'),
                                                             Punteria__c = (Integer)result.get('accuracy'),
                                                             Chance_de_Efecto__c = (Integer)result.get('effect_chance'),
                                                             Objetivo__c = (String) targetData.get('name'),
                                                             Prioridad__c = (Integer)result.get('priority'),
                											 Efecto__c = (efectData.size() == 0 ? '' : ((String)((Map<String, Object>) efectData[0]).get('short_effect'))),
                                                             Poder__c = (Integer)result.get('power'),
                                                             Pp__c = (Integer)result.get('pp'),
                                                             Tipo__c = (String)typeData.get('name'));
                											                									
                movimientos.add(movimiento);
                
            }
            
        }
        insert movimientos;
    }
    global void finish(Database.BatchableContext BC) {
        system.debug('finish');
    }
}