force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Tipos__c.field-meta.xml
<CustomField>
    <fullName>Tipos__c</fullName>
    <label>Tipos</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/pokemonServiceTest.cls
@isTest
public class pokemonServiceTest {
    @isTest 
    static void getFilterPokemonTestOk() {
        
        Pokemon__c pokemon = new Pokemon__c(Name='Pikachu', Tipos__c='Electric', ExtId__c=25);       
        insert pokemon;
        
        List<Pokemon__c> pokemons = PokemonService.getFilterPokemon('Pik', 'Electric', 1);
        
        System.assertEquals(1, pokemons.size());
        System.assertEquals('Pikachu', pokemons[0].Name);
    }
    
    @isTest 
    static void getFilterPokemonTestKo() {
        List<Pokemon__c> pokemons = PokemonService.getFilterPokemon('', '', -1);
        
        System.assertEquals(0, pokemons.size());
    }
}