force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Ataque__c.field-meta.xml
<CustomField>
    <fullName>Ataque__c</fullName>
    <label>Ataque</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Defensa__c.field-meta.xml
<CustomField>
    <fullName>Defensa__c</fullName>
    <label>Defensa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Generacion__c.field-meta.xml
<CustomField>
    <fullName>Generacion__c</fullName>
    <formula>IF(ExtId__c &lt;= 151, 1,
IF(ExtId__c &lt;= 251, 2,
IF(ExtId__c &lt;= 386, 3,
IF(ExtId__c &lt;= 493, 4,
IF(ExtId__c &lt;= 649, 5,
IF(ExtId__c &lt;= 721, 6,
IF(ExtId__c &lt;= 809, 7,
IF(ExtId__c &lt;= 898,8,0))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Generacion</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Tipos__c.field-meta.xml
<CustomField>
    <fullName>Tipos__c</fullName>
    <label>Tipos</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Velocidad__c.field-meta.xml
<CustomField>
    <fullName>Velocidad__c</fullName>
    <label>Velocidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Vida__c.field-meta.xml
<CustomField>
    <fullName>Vida__c</fullName>
    <label>Vida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/pokemonService.cls
public with sharing class pokemonService {
    @AuraEnabled(cacheable=true)
    public static List<Pokemon__c> getFilterPokemon(String textoBusqueda, String tipo, Integer generacion) {

        String valorContenido = '%' + textoBusqueda + '%';
        String query =  'SELECT '+
 	           		    'Id, '+
            		    ' Name, '+
            		    ' ExtId__c, '+
            		    ' image__c, '+
                        ' Tipos__c, '+
                        ' Vida__c, '+
                        ' Velocidad__c, '+
                        ' Defensa__c, '+
                        ' Ataque__c, '+
                        ' Generacion__c '+
            		    ' FROM Pokemon__c ';

        if(valorContenido != ''){
            query = query + 'WHERE Name LIKE :valorContenido ';
        }

        if(tipo != 'All'){
            query = query +'AND Tipos__c INCLUDES(:tipo) ';
        }

        if(generacion != 0){
            query = query + 'AND Generacion__c =: generacion ';
        }

		query = query + 'ORDER BY ExtId__c';
        
        return Database.query(query);

    }
}